global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'vivobook'
    static_configs:
      - targets: ['REDACTED']

  - job_name: 'msi'
    static_configs:
      - targets: ['REDACTED']

  - job_name: 'nas'
    static_configs:
      - targets: ['REDACTED']
